#!/usr/bin/env bash
read -p "This will undo ALL changes in the HandsOnMaterial folder, including any new files you created there. ARE YOU SURE? [y/N]" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
        # Discard all changes and restore repository to the last commit
        git reset --hard HEAD
        # Remove all untracked files and directories
        git clean -fd
else
        echo "Aborted."
fi
